### ISSUE TITLE
Moving some KSP utils to compiler-util

### ISSUE THREAD

**Issue by WhosNickDoglio** [ZacSweers/anvil#74]
👋 

I'm currently working on migrating an Anvil plugin to support KSP and this work, there's a number of KSP util functions in the `compiler` module that are would be useful.  I'm looking at functions in these files: 

- https://github.com/ZacSweers/anvil/blob/main/compiler/src/main/java/com/squareup/anvil/compiler/codegen/ksp/KspUtil.kt
- https://github.com/ZacSweers/anvil/blob/main/compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/DaggerGenerationUtils.kt

Would you be open to a PR moving these into the compiler-utils module?

**Comment by ZacSweers** [comment]
Yep!
